### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.func')错误

### ISSUE THREAD

**Issue by 123dong** [shiwenwen/react-native-swRefresh#18]
报错误：undefined is not an object (evaluating '_react.PropTypes.func')

执行完 npm install react-native-swRefresh --save
引入作者demo中main.js,跑项目直接就报错，
不知道，是依赖引入有问题？还是什么问题，

这是我的配置
 "dependencies": {
    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-pull": "^2.0.2",
    "react-native-swRefresh": "^1.2.3",
    "react-native-swiper": "^1.5.13",
    "react-native-tab-navigator": "^0.3.4"
  },

**Comment by 123dong** [comment]
这个问题我自问自答一波啊哈，各位见谅！！！
主要由于作者这个开源库，版本太老了，PropTypes导入有问题导致的，
在React 15.5.0 之后的版本，我们就不要再已这种方式导出PropTypes了import React, { Component, PropTypes} from 'react'，
应是更换为：import PropTypes from 'prop-types'，安装prop-types库  npm install prop-types --save
所以如果还需要用作者的库，请修改作者库中代码即可
打完收工！！！谢谢

**Comment by linlinNB** [comment]
@123dong 好，支持你，非常感谢，解决了大问题
