### ISSUE TITLE
安卓进入界面,如果数据较少,少于一屏的话. 下拉刷新部位会凸出来.

### ISSUE THREAD

**Issue by pheromone** [shiwenwen/react-native-swRefresh#6]
安卓进入界面,刷新部位会凸出来.

**Comment by shiwenwen** [comment]
这个都开放了  自己处理 可以将状态设置为已无更多数据或者根据state隐藏上拉加载 数据是多是少 怎么处理 自己是的逻辑处理 


Sent from Mail Master
在2017年01月17日 14:37，少停 写道:

Reopened #6.
